FROM node:14.21.2-alpine3.16

WORKDIR /app

COPY package*.json .
COPY .env .

RUN npm install

COPY . .

RUN npm run build

COPY entrypoint.sh .
COPY wait-for-it.sh .


RUN chmod +x entrypoint.sh
RUN chmod +x wait-for-it.sh

CMD [ "sh", "./entrypoint.sh" ]
